### ISSUE TITLE
Display features that are covered by spec on opencost homepage

### ISSUE THREAD

**Issue by dwbrown2** [kubecost/opencost-website#24]
This particular feature is included in the OpenCost implementation but not in the spec. It's created some confusion. My proposal is that we remove it. 

<img width="312" alt="image" src="https://user-images.githubusercontent.com/298359/175424043-63d13a8b-8eee-4e67-ada1-d285760b7e7e.png">

**Comment by prakharporwal** [comment]
I am starting on this.

**Comment by dwbrown2** [comment]
Looks great, @prakharporwal! Will merge now.
