### ISSUE TITLE
Add LF footer and follow CNCF website guidelines 

### ISSUE THREAD

**Issue by dwbrown2** [kubecost/opencost-website#25]
As part of CNCF onboarding we'll want to support this: https://github.com/cncf/foundation/blob/master/website-guidelines.md

**Comment by Adam-Stack-PM** [comment]
Helpful project examples https://www.cncf.io/sandbox-projects/  not all have the logo added by most do.

**Comment by dwbrown2** [comment]
@avrodrigues5 still interested in taking a look at this one today or better for @srpomeroy to pick up? 

cc @Adam-Stack-PM

**Comment by avrodrigues5** [comment]
Spoke with @Adam-Stack-PM , @srpomeroy is best person to complete this.

**Comment by dwbrown2** [comment]
Re-opened after accidentally closing...

**Comment by srpomeroy** [comment]
I appreciate the vote of confidence. I guarantee you I am not the best person to do this. But I will figure it out.
