### ISSUE TITLE
Can we add a simple FAQ to OpenCost documentation? 

### ISSUE THREAD

**Issue by dwbrown2** [kubecost/opencost-website#3]
Have this draft doc started:

https://docs.google.com/document/d/1Ljc8udVi4gKSPV7efwbdUnAJGofZRVMwS7lAFAhxr6Q/edit

cc @elenalape @AjayTripathy

**Comment by elenalape** [comment]
@dwbrown2 the FAQ isn't completed, should be good to go tomorrow 👍🏻

**Comment by AjayTripathy** [comment]
https://github.com/kubecost/opencost-website/pull/6

Here's a quick template, we an finish editing the markdown there or in the google doc, I have a handy tool to go from docs -> markdown as well so when it's done I can add the rest as well.

**Comment by dwbrown2** [comment]
Approved & merged! Thank you.
