### ISSUE TITLE
Broken link on "documentation" page

### ISSUE THREAD

**Issue by jcharcalla** [kubecost/opencost-website#39]
There is a broken link on the "documentation" page, the strange thing is that depending on the path taken to the page will determine if the link is broken or not. This leads me to believe the issue may be related to the "Documentation" link on the main page and not the "documentation" page itself.

To reproduce:
Scroll to the bottom of the page and click the "Documentation" link. Note: Clicking the documentation link on the top of the page will not result in the issue.
<img width="1232" alt="Screen Shot 2022-08-23 at 2 37 16 PM" src="https://user-images.githubusercontent.com/17748044/186238881-ab391806-91f4-4805-bd72-94d792073d88.png">

Click the "Install options" on the page which will result in a broken link. Note the missing trailing slash / in the address bar from the link on the previous page. This is most likely the issue.
<img width="1235" alt="Screen Shot 2022-08-23 at 2 38 18 PM" src="https://user-images.githubusercontent.com/17748044/186239361-a4171ba5-3321-4e80-9f82-af489728e8ac.png">

After clicking the link, it fails because /docs/ is missing from the path.
<img width="1232" alt="Screen Shot 2022-08-23 at 2 40 42 PM" src="https://user-images.githubusercontent.com/17748044/186239935-8f69a474-d344-4a22-b342-da369d3ba68b.png">

This screen shot is from following the "Documentation" link at the top of the page. Note that it includes a trailing slash / in the URL.
<img width="1144" alt="Screen Shot 2022-08-23 at 2 42 43 PM" src="https://user-images.githubusercontent.com/17748044/186240277-01a68fdc-0042-475f-8f08-b2d3411c65a0.png">

**Comment by dwbrown2** [comment]
Great catch! Fix should be here: https://github.com/kubecost/opencost-website/pull/40
