### ISSUE TITLE
Broken link on new install page

### ISSUE THREAD

**Issue by dwbrown2** [kubecost/opencost-website#44]
This page: https://github.com/kubecost/opencost-website/blob/main/docs/install.md

Currently has a 404 link here: https://github.com/kubecost/opencost-website/blob/main/docs/install.md

We should be sure to test changes on this page really careful given that mistakes will likely mean users never get Opencost.

**Comment by jessegoodier** [comment]
Agreed. fixed.
Vercel is great, but in this case the opencost repo change at the same time made it more difficult to test.

Would love to get your thoughts on the changes and anything else you'd like to see here.

**Comment by dwbrown2** [comment]
Nice, thanks for the quick fix! Can take a closer look soon too and will report back any ideas.
