### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by hs-07** [kubecost/opencost-website#53]
This is a great looking website but a small feature which is dark mode is absent in it so I would like to contribute to site in order to enable DARK MODE.
Request you to assign me the issue and also label it as Hacktoberfest-accepted.
Thank you!😊

**Comment by dwbrown2** [comment]
This would make us very happy! 😄

**Comment by dwbrown2** [comment]
Were you able to find a solution? I'm unfortunately not familiar with this package.

**Comment by hs-07** [comment]
@dwbrown2 
Yes i did found the solution.
Previously I wasnt familiar with Docusaurus, but I learnt it and found the solution.😊

**Comment by hs-07** [comment]
I have made the PR, @dwbrown2   sir 
Have a look and inform me if any changes are required.
Thank you

**Comment by dwbrown2** [comment]
Awesome, @hs-07! @jjarrett21 any chance you might be able to take a quick look while @nealormsbee is OOO? 

PR is here: https://github.com/kubecost/opencost-website/pull/54

**Comment by nealormsbee** [comment]
🚨 🚨 🚨 

Thank you @hs-07! This is awesome, site looks great.

**Comment by hs-07** [comment]
@nealormsbee 
It's my pleasure...😇✌️ You all loved it...
Thank you @dwbrown2  for assigning me the issue...and giving me such opportunity, and yaa I had tagged you @dwbrown2 in a LinkedIn post😅🙈 , hope you saw
