### ISSUE TITLE
Partners section: AWS logo not aligned

### ISSUE THREAD

**Issue by sudarshanshenoy** [kubecost/opencost-website#55]
The AWS logo is not vertically aligned correctly. 
 
![image](https://user-images.githubusercontent.com/13462896/196006356-c0b6073b-74ea-4692-987a-c4d7308c99ff.png)

The container around the image should have height h-52 similar to other logos.
![image](https://user-images.githubusercontent.com/13462896/196006449-282246b1-b2ad-44fc-9104-18a8693bd669.png)

**Comment by dwbrown2** [comment]
Strange, don't know why this wasn't caught before. Thanks for sharing. 

PR out to fix: https://github.com/kubecost/opencost-website/pull/56
