### ISSUE TITLE
Review dedicate Slack room links

### ISSUE THREAD

**Issue by dwbrown2** [kubecost/opencost-website#9]
When creating this project website, one thing we observed is that most k8s projects have their own Slack workspaces, e.g.

https://github.com/open-policy-agent/opa
https://github.com/cilium/cilium

We thought it was a bit too early to create a dedicated workspace and still be able to manage it effectively when we launched. I propose revisiting this soon. I suspect we'll want to create a new workspace but there may be other approaches.

**Comment by trentbroderick** [comment]
Would be happy to contribute in building the workspace out when the timing feels right!

**Comment by hs-07** [comment]
> When creating this project website, one thing we observed is that most k8s projects have their own Slack workspaces, e.g.
> 
> https://github.com/open-policy-agent/opa https://github.com/cilium/cilium
> 
> We thought it was a bit too early to create a dedicated workspace and still be able to manage it effectively when we launched. I propose revisiting this soon. I suspect we'll want to create a new workspace but there may be other approaches.

That would be great and will definitely make the converstaions more easy and fast. Would love to contribute in building a healthy community.

**Comment by dwbrown2** [comment]
Current plan is to move to CNCF slack! @alexkubecost have an invite we can add to the website?
